name: Build macOS
on:
  workflow_call:
    inputs:
      release-name:
        description: 'Tag passed from the caller workflow'
        default: ${{ github.sha }}
        required: false
        type: string
  workflow_dispatch:

jobs:
  build:
    name: 'Build on macOS 14 with M1'
    runs-on: macos-14
    timeout-minutes: 5

    env:
      BASE_ROOT_DIR: ${{ github.workspace }}
      TARGET_ARCH: macos-sonoma-arm64

    steps:
      - name: Setup variables
        run: |
          RELEASE_NAME=${{ inputs.release-name }}
          if [[ -z "$RELEASE_NAME" ]]; then
            RELEASE_NAME=${{ github.sha }}
          fi
          RELEASE_NAME=${RELEASE_NAME#v}
          echo "RELEASE_FOLDER=cpuminer-scash-$RELEASE_NAME-$TARGET_ARCH" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Clang version
        run: |
          sudo xcode-select --switch /Applications/Xcode_15.0.app
          clang --version

      - name: Cache brew
        uses: actions/cache@v4.2.0
        with:
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Frameworks
            /usr/local/bin
            /usr/local/opt
          key: ${{ runner.os }}-brew-cache

      - name: Install Homebrew packages
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          brew upgrade
          brew install autoconf automake libtool pkg-config curl coreutils
          brew link curl --force

      - name: Compile and build
        run: |
          autoreconf -fi
          ./autogen.sh
          ./configure CC=clang CXX=clang++
          make -j 3

      - name: Test benchmarking
        run: |
          ./minerd --version
          ./minerd --benchmark

      - name: Package artifact
        run: |
          mkdir $RELEASE_FOLDER
          cp -a minerd $RELEASE_FOLDER
          cd $RELEASE_FOLDER && sha256sum * >SHA256SUMS && cd ..
          # sha256sum $RELEASE_FOLDER/* >$RELEASE_FOLDER/SHA256SUMS
          ARTIFACT_FILENAME=$RELEASE_FOLDER.tgz
          tar -czvf $ARTIFACT_FILENAME $RELEASE_FOLDER
          echo "ARTIFACT_FILENAME=$ARTIFACT_FILENAME" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_FILENAME }}
          path: ${{ env.ARTIFACT_FILENAME }}
          retention-days: 1
          if-no-files-found: error

      - name: Cancel parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.4

